[general]
import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[window]
blur = true
opacity = 0.8

[font.normal]
family = "UbuntuMono Nerd Font"

[font.bold]
family = "UbuntuMono Nerd Font"

[font.italic]
family = "UbuntuMono Nerd Font"

[font]
size = 16
