[general]
import = ["~/.config/alacritty/themes/themes/kanagawa.toml"]

[window]
blur = true
opacity = 0.8

[font.normal]
family = "Hack Nerd Font"

[font.bold]
family = "Hack Nerd Font"

[font.italic]
family = "Hack Nerd Font"

[font]
size = 16
